#!/bin/tcsh

#SBATCH --job-name=make-bw                            # job name
#SBATCH --partition=super                                # select partion from 128GB, 256GB, 384GB, GPU and super
#SBATCH --nodes=1                                        # number of nodes requested by user
#SBATCH --time=0-72:00:00                                 # run time, format: D-H:M:S (max wallclock time)
#SBATCH --output=serialJob.%j.out                        # standard output file name
#SBATCH --error=serialJob.%j.time                        # standard error output file name
#SBATCH --mail-user=aishwarya.sundaresan@utsouthwestern.edu      # specify an email address
#SBATCH --mail-type=FAIL                                  # send email when job status change (start, end, abortion and etc.)

module load samtools
module load picard/1.117
module load bedtools
module load UCSC_userApps
module load igvtools/2.3.71

foreach sample(\
    Cut_Tag_BG4_MABE_KO144_merged\
    Cut_Tag_BG4_MABE_WT26_LB_KAPA_S2\
)  

echo $sample

     set CHROM_SIZE = /project/apps_database/iGenomes/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa.fai
    #set CHROM_SIZE = /project/apps_database/iGenomes/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa.fai

    bedtools genomecov -ibam /project/GCRB/Banaszynski_lab/shared/Yu-Ching/BG4_Cut_and_Tag/WT26_ATRX_KO_reanalysis/downsample_out/downsample.sh-1.1.0/$sample.nodups.downsampled.bam -bga > /project/GCRB/Banaszynski_lab/shared/Yu-Ching/BG4_Cut_and_Tag/WT26_ATRX_KO_reanalysis/bw_files/$sample.nodup.bedGraph

    sort -k1,1 -k2,2n /project/GCRB/Banaszynski_lab/shared/Yu-Ching/BG4_Cut_and_Tag/WT26_ATRX_KO_reanalysis/bw_files/$sample.nodup.bedGraph > /project/GCRB/Banaszynski_lab/shared/Yu-Ching/BG4_Cut_and_Tag/WT26_ATRX_KO_reanalysis/bw_files/$sample.nodup.sorted.bedGraph

    bedGraphToBigWig /project/GCRB/Banaszynski_lab/shared/Yu-Ching/BG4_Cut_and_Tag/WT26_ATRX_KO_reanalysis/bw_files/$sample.nodup.sorted.bedGraph $CHROM_SIZE /project/GCRB/Banaszynski_lab/shared/Yu-Ching/BG4_Cut_and_Tag/WT26_ATRX_KO_reanalysis/bw_files/$sample.nodup.bw


end
